/** Domain barrel — every symbol previously exported from the monolithic store.tsx, re-exported at the same paths so `from "./store"` / `from "../store"` call sites are unaffected by the split. */
export type {
  DataGridSyncProps,
  SelectionChangeDetails,
  AnyColumnDef,
  AnyCellType,
  ColumnDefOf,
  ClipboardProcessCtx,
  SelectLineActionOptions,
  CellPatch,
  RowPatch,
  UpdateCellsOptions,
  UpdateCellsReorder,
  CellErrorTarget,
  CellErrorEntry,
  DataGridStoreState,
  DataGridActions,
  DataGridStore,
  DataGridProviderProps,
  DataGridCellState,
  DataGridRowCellState,
} from "./types";
export { DataGridProvider, useDataGridStoreApi } from "./provider";
export { cellErrorKey } from "./compute";
export { getFocusCell } from "./hooks";
export {
  useDataGridActions,
  useDataGridCellTypes,
  useDataGridScrollToCell,
  useDataGridFillHandlers,
  useDataGridReadOnly,
  useDataGridKeymap,
  useDataGridLabels,
  useDataGridActiveCell,
  useDataGridHasActiveCell,
  useDataGridActiveColumn,
  useDataGridSelection,
  useDataGridGetSelectionValues,
  useDataGridOverlayPlugins,
  useDataGridRowBands,
  useDataGridEditing,
  useDataGridEditingError,
  useDataGridCellErrors,
  useDataGridRowHasError,
  useDataGridViewIndex,
  useDataGridViewStale,
  useDataGridVisibleColumns,
  useDataGridAllColumns,
  useDataGridIsColumnHidden,
  useDataGridColumnWidth,
  useDataGridColumnWidths,
  useDataGridSortState,
  useDataGridHeaderClickBehavior,
  useDataGridColumnFeatureFlags,
  useDataGridFilterState,
  useDataGridJoinOperator,
  useDataGridSearchText,
  useDataGridSearchMatches,
  useDataGridSearchCapped,
  useDataGridIsSearchMatch,
  useDataGridRow,
  useDataGridRowId,
  useDataGridRowIds,
  useDataGridRowIdToViewRow,
  useDataGridRowCount,
  useDataGridIsRowSelected,
  useDataGridIsRowChannelSelected,
  useDataGridIsRowCellSelected,
  useDataGridIsCellActive,
  useDataGridIsCellEditing,
  useDataGridCellInitialText,
  useDataGridCellEditingError,
  useDataGridCellRejectionCount,
  useDataGridCellState,
  useDataGridRowCellState,
  useDataGridRowMarkers,
  useDataGridSelectionConfig,
  useDataGridAllRowsSelected,
} from "./hooks";
